#:include memorymapview.kv

<PlayScreen>:
    GridLayout:
        spacing: "20dp"
        cols: 1

        MDToolbar:
            id: toolbar
            title: 'Play Screen'
            left_action_items: [["arrow-left", lambda x: app.change_screen('home_screen','right')]]
            right_action_items: [["check-bold", lambda x: root.actionButton() ]]

        MemoryMapView:
            id: mapViewer